name: Strapi ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    #################################
    # AWS Credentials
    #################################
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    #################################
    # Setup Terraform
    #################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    #################################
    # Wait For AWS Resources â­ VERY IMPORTANT
    #################################
    - name: Wait
      run: sleep 60

    #################################
    # Get Terraform Output
    #################################
    - name: Get Repo URL
      run: |
        terraform output repo_url > repo.txt

    #################################
    # Docker Login + Build + Push
    #################################
    - name: Build and Push Image
      run: |
        REPO_URI=$(cat repo.txt)

        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin \
        $(echo $REPO_URI | cut -d'/' -f1)

        docker build -t $REPO_URI:latest .

        docker push $REPO_URI:latest

    #################################
    # Deploy ECS
    #################################
    - name: Deploy ECS Service
      run: |
        aws ecs update-service \
        --cluster noor-strapi-final-cluster-v6 \
        --service noor-strapi-service-v6 \
        --force-new-deployment
