name: Strapi ECS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    #################################
    # Checkout Code
    #################################
    - uses: actions/checkout@v3

    #################################
    # Install Dependencies
    #################################
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install jq -y

    #################################
    # AWS Credentials
    #################################
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    #################################
    # Terraform Setup
    #################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    #################################
    # Get Clean Terraform Output â­
    #################################
    - name: Get Repo URI
      run: |
        REPO_URI=$(terraform output -json repo_uri | jq -r '.value')

        echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV

    #################################
    # Docker Login + Build + Push
    #################################
    - name: Docker Login + Push
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin \
        $(echo $REPO_URI | cut -d'/' -f1)

        docker build -t $REPO_URI:latest .

        docker push $REPO_URI:latest

    #################################
    # Deploy ECS
    #################################
    - name: Deploy ECS Service
      run: |
        aws ecs update-service \
        --cluster noor-strapi-final-cluster-v6 \
        --service noor-strapi-service-v6 \
        --force-new-deployment
