name: Deploy Strapi ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    #################################
    # Checkout Code
    #################################
    - uses: actions/checkout@v3

    #################################
    # Install jq
    #################################
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install jq -y

    #################################
    # AWS Credentials
    #################################
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    #################################
    # Setup Terraform
    #################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    #################################
    # Get Repo URI â­ Clean Method
    #################################
    - name: Get Repo URI
      run: |
        REPO_URI=$(terraform output -raw repo_uri)

        echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV

    #################################
    # Login + Build + Push Image
    #################################
    - name: Docker Login + Build + Push
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin \
        $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

        docker build -t $REPO_URI:latest .

        docker push $REPO_URI:latest

    #################################
    # Deploy ECS
    #################################
    - name: Deploy ECS
      run: |
        aws ecs update-service \
        --cluster noor-strapi-final-cluster-dev \
        --service noor-strapi-service-dev \
        --force-new-deployment
